### ISSUE TITLE
MongoDB Object ID versiyonu

### ISSUE THREAD

**Issue by serkaneo** [emreuenal/turkiye-il-ilce-sokak-mahalle-veri-tabani#1]
Merhaba Emre hocam,
Mongo db veritabanını Object ID versiyonunu yapabilir misiniz? 
Buna çok ihtiyacım var ve bir türlü çözüm bulamadım.
Çok teşekkürler
Saygılarımla
Serkan

**Comment by emreuenal** [comment]
Merhaba Serkan Bey,

Scripti çalıştırdım şimdi, veritabanı oluşur oluşmaz dump klasörüne atarım.

**Comment by emreuenal** [comment]
@serkaneo ObjectID‘li dump‘i dumps klasorunden indirebilirsiniz
