### ISSUE TITLE
JSON Formatı

### ISSUE THREAD

**Issue by hakanoktay** [emreuenal/turkiye-il-ilce-sokak-mahalle-veri-tabani#2]
Hocam öncelikle teşekkür ederim. Postgres importunda sorun var. problem olmadan postgrs'e çevirmek için öncelikle JSON dump aldım. [linkte ulaşılabilir.](https://github.com/hakanoktay/il-ilce-mahalle-sokak)  postgres çevirisi tamamlanıca onuda eklerim. Eline sağlık, çok faydalı oldu.

**Comment by emreuenal** [comment]
> Hocam öncelikle teşekkür ederim. Postgres importunda sorun var. problem olmadan postgrs'e çevirmek için öncelikle JSON dump aldım. [linkte ulaşılabilir.](https://github.com/hakanoktay/il-ilce-mahalle-sokak) postgres çevirisi tamamlanıca onuda eklerim. Eline sağlık, çok faydalı oldu.

Merhaba Hakan Bey;
Ah, aynen şimdi bir deneme fırsatım oldu. Sunucuda birden fazla ve farklı versiyonlarda postgresql kurulu, büyüm ihtimalle yanlışlıkla eski versiyonlardan birinin pg_dump'ını kullandım. 

Mart ayı için dumplar oluşturacaktım zaten, bitince onlar ile beraber tekrar dump alır yüklerim gece.

Teşekkür Ederim

**Comment by emreuenal** [comment]
@hakanoktay Mart Ayı dumpları eklendi. PostgreSQL dump'ı test ettim sorunsuz bir şekilde importlanabiliyor. Bildirim için tekrar teşekkür ederim.
