### ISSUE TITLE
pgadminde hata veriyor

### ISSUE THREAD

**Issue by yasartaymaz** [emreuenal/turkiye-il-ilce-sokak-mahalle-veri-tabani#4]
"pg_restore: error: input file appears to be a text format dump. Please use psql."

**Comment by emreuenal** [comment]
Merhaba,

hata mesajinda da soylendigi gibi psql komutu ile dump'i import edebilirsiniz.
Bunun icin veri tabani sunucusuna ssh ile baglanin, postgres  kullanicisina gecis yaparak dump dosyasini onceden psql ya da pgadmin uzerinden olusturmus oldugunuz bos veri tabanina import edin:

`psql lokal_bos_veri_tabani < dump_dosyasi`

ya da root olarak:

`psql -d lokal_bos_veri_tabani -U postgres -f dump_dosyasi
`

**Comment by yasartaymaz** [comment]
teşekkürler yönergeler için.
